apiVersion: apps/v1
kind: Deployment 
metadata:
 name: livenessprobe
 labels:
  app: livenessprobe

spec:
 replicas: 2
 selector:
  matchLabels:
   app: livenessprobe
 template:
   metadata:
    labels:
     app: livenessprobe
   spec: 
    containers:
    - name: livenessprobe
      image: registry.k8s.io/e2e-test-images/agnhost:2.40
      args:
      - liveness
      livenessProbe:
        httpGet:
         path: /healthz
         port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:  
         path: /healthz
         port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
         