apiVersion: v1
kind: Pod
metadata:
  name: nginx-deployment
  labels:
    env: test
    app: nginx
spec:
  nodeName: kind-worker2
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
