apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-dev
  labels:
    app: mysql
    env: dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dev
  namespace: dev
  labels:
    app: mysql
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mysql-pv-dev
  storageClassName: manual