apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dev
  labels:
    app: mysql
    env: dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3          # Add this line
  hostPath:
    path: /mnt/dev/data/mysql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dev
  labels:
    app: mysql
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mysql-pv-dev
  storageClassName: gp3          # Make it same as PV
