apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
  labels:
    env: test
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

